linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/gilbertrios/terraform-provider-utils

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - examples

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
